//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v14.2.0+1b21caa
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>Projects Page</summary>
	[PublishedModel("projectsPage")]
	public partial class ProjectsPage : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		public new const string ModelTypeAlias = "projectsPage";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<ProjectsPage, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public ProjectsPage(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Contact Section - Background Color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactSectionBackgroundColor")]
		public virtual string ContactSectionBackgroundColor => this.Value<string>(_publishedValueFallback, "contactSectionBackgroundColor");

		///<summary>
		/// Project Section - Card Calendar Icon
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectSectionCardCalendarIcon")]
		public virtual string ProjectSectionCardCalendarIcon => this.Value<string>(_publishedValueFallback, "projectSectionCardCalendarIcon");

		///<summary>
		/// Project Section - Card Content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectSectionCardContent")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel ProjectSectionCardContent => this.Value<global::Umbraco.Cms.Core.Models.Blocks.BlockListModel>(_publishedValueFallback, "projectSectionCardContent");

		///<summary>
		/// Project Section - Card Link Arrow
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectSectionCardLinkArrow")]
		public virtual string ProjectSectionCardLinkArrow => this.Value<string>(_publishedValueFallback, "projectSectionCardLinkArrow");

		///<summary>
		/// Project Section - Card Link Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectSectionCardLinkText")]
		public virtual string ProjectSectionCardLinkText => this.Value<string>(_publishedValueFallback, "projectSectionCardLinkText");

		///<summary>
		/// Project Section - Card Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectSectionCardText")]
		public virtual string ProjectSectionCardText => this.Value<string>(_publishedValueFallback, "projectSectionCardText");

		///<summary>
		/// Project Section - Pagination Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectSectionPaginationImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ProjectSectionPaginationImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "projectSectionPaginationImage");

		///<summary>
		/// Project Section - Support Background Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectSectionSupportBackgroundImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ProjectSectionSupportBackgroundImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "projectSectionSupportBackgroundImage");

		///<summary>
		/// Project Section - Support Input Icon
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectSectionSupportInputIcon")]
		public virtual string ProjectSectionSupportInputIcon => this.Value<string>(_publishedValueFallback, "projectSectionSupportInputIcon");

		///<summary>
		/// Project Section - Support Input Placeholder
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectSectionSupportInputPlaceholder")]
		public virtual string ProjectSectionSupportInputPlaceholder => this.Value<string>(_publishedValueFallback, "projectSectionSupportInputPlaceholder");

		///<summary>
		/// Project Section - Support Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectSectionSupportText")]
		public virtual string ProjectSectionSupportText => this.Value<string>(_publishedValueFallback, "projectSectionSupportText");

		///<summary>
		/// Project Section - Support Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectSectionSupportTitle")]
		public virtual string ProjectSectionSupportTitle => this.Value<string>(_publishedValueFallback, "projectSectionSupportTitle");

		///<summary>
		/// Project Section - Tags
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectSectionTags")]
		public virtual global::System.Collections.Generic.IEnumerable<string> ProjectSectionTags => this.Value<global::System.Collections.Generic.IEnumerable<string>>(_publishedValueFallback, "projectSectionTags");

		///<summary>
		/// Project Section - Tag Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectSectionTagTitle")]
		public virtual string ProjectSectionTagTitle => this.Value<string>(_publishedValueFallback, "projectSectionTagTitle");

		///<summary>
		/// Title Section - Background Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("titleSectionBackgroundImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops TitleSectionBackgroundImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "titleSectionBackgroundImage");

		///<summary>
		/// Title Section - Link Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("titleSectionLinkText")]
		public virtual string TitleSectionLinkText => this.Value<string>(_publishedValueFallback, "titleSectionLinkText");

		///<summary>
		/// Title Section - Link Url
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("titleSectionLinkUrl")]
		public virtual string TitleSectionLinkUrl => this.Value<string>(_publishedValueFallback, "titleSectionLinkUrl");

		///<summary>
		/// Title Section - Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("titleSectionTitle")]
		public virtual string TitleSectionTitle => this.Value<string>(_publishedValueFallback, "titleSectionTitle");
	}
}
